### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jospoortvliet**
Let's say Nextcloud. And let's tell ppl what is up with the 'deprecated' status, why etc.

### CODE REVIEW

**Comment by MariusBluem** [comment]
Please add a small note about the support in the info.xml and link to Collabora Online as recommender „replacement“.

**Comment by jospoortvliet** [comment]
Pls do a separate pull for the info.xml, I did this in the web interface so I can't do that. I did add a link to Collabora Online.

**Comment by cmroanirgo** [comment]
I've noticed that the 'recommended' replacements all require a docker host. This is *not* a feasible solution in many situations, and many will still prefer this low-key solution.

**Comment by pboesch** [comment]
How can I install Collabora Online on a FreeBSD host ?

**Comment by jospoortvliet** [comment]
The conversation is going off in random directions so let's merge this thingy 😄

**Pull request merged**
