### PR TITLE
Adapt to Nc12?

### PR DESCRIPTION
**Pull request by blizzz**
Straight forward port, lets see

* [x] requires https://github.com/nextcloud/server/pull/5315

### CODE REVIEW

**Comment by blizzz** [comment]
The app can be enabled, is however broken otherwise. Alas, this is caused by Nc 12.

**Comment by blizzz** [comment]
See https://github.com/nextcloud/server/issues/5314

**Comment by blizzz** [comment]
fyi @MariusBluem @jospoortvliet since you were curious about this

**Comment by icewind1991** [comment]
Broken for me

image

**Comment by pboesch** [comment]
Works for me on NC12 ! thx

**Comment by icewind1991** [comment]
Retested, works fine when you open a document trough the app, but when you open one from the files app you get unexpected behaviour:

image

**Comment by blizzz** [comment]
@icewind1991 this is the viewer component, which opens from Files. Same as in Nc 11. Was it different any other time?

**Comment by blizzz** [comment]
… to go to edit mode from files use "edit" from the three dot menu:

spectacle w23262

**Pull request merged**
